### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by carlosingles** [mark-hahn/space-brush#5]
I've just pushed through commits that updates SpaceBrush to use object observers. The code can still be optimised and cleaned up, but for now I've got basic functionality working.

I've also migrated the space-pen README and updated it to reflect how SpaceBrush will work - there are still bits and pieces that need to be updated.

In terms of reaching 1.0 status, some things I think that should be considered:
- Are native templates necessary? I would think that a better implementation would be to use Subviews since they can have a model attached to them
- I saw your message on the Atom Slack in regards to [incremental-dom](https://github.com/google/incremental-dom). It looks promising and it looks like it would be easier to manage changes over fast-dom

Let me know your thoughts

**Comment by mark-hahn** [comment]
I feel bad that I haven't had time to help or even follow your work. If you
pull this off then maybe it should be your repo.

**Comment by carlosingles** [comment]
No worries, I've updated the repo once again after doing some reading/thinking and have managed to update my repo to reflect the changes:

https://github.com/carlosingles/space-brush

You can read about the way I've made `space-brush` work in the README

What's missing (but not too breaking) is directives, which would be the next step before I would be happy to use this in production.

**Comment by mark-hahn** [comment]
> I would be happy to use this in production.

I'm starting a new project for a start-up I've joined. If I use space-brush
I'll have an excuse to help out.
